
KEYS = [
    "ENV",
    "URL_OF_DIRECTUS_INPROD",
    "URL_OF_DIRECTUS_NOPROD",
    "ROUTE_OF_DIRECTUS_FOR_DGEASS_PRODUCT",
    "ROUTE_OF_DIRECTUS_FOR_DGEASS_ORDER",
    "ROUTE_OF_DIRECTUS_FOR_DGEASS_TRANSACTION_LOG",
    "CINETPAY_API_KEY",
    "CINETPAY_SITE_ID",
    "CINETPAY_CHECK_URL",
    "LISTMONK_API_URL",
    "LISTMONK_API_USERNAME",
    "LISTMONK_API_PASSWORD",
    "MINIO_PROXY",
    "MINIO_SECURE",
    "MINIO_HOST",
    "MINIO_PORT",
    "MINIO_ACCESS_KEY",
    "MINIO_SECRET_KEY",
    "MINIO_BUCKET_NAME"
]

N_PROCESSOR = 2

ORDER_STATUS_STARTED = "started"
ORDER_STATUS_COMPLETED = "completed"
ORDER_STATUS_ABANDONED = "abandoned"
ORDER_STATUS_FAILED = "failed"


TRANSACTION_STATUS_PENDING = 1
TRANSACTION_STATUS_ACCEPTED = 2
TRANSACTION_STATUS_REFUSED = 3

APP_NAME = "DIGITAL-GEASS-WORKER"
LOG_DIRECTORY = "logs"
LOG_CONST = "{}, {}"
DATA_DIRECTORY = "data"
TEMP_DIRECTORY = "temp"
NLIMIT = 3000
MAX_RETRIES = 3

MINIO_DEFAULT_DURATION = 30
